//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5420
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZZD.ERP.WinUI.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CZZD.ERP.WinUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap account_management {
            get {
                object obj = ResourceManager.GetObject("account_management", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap account_management_enabled {
            get {
                object obj = ResourceManager.GetObject("account_management_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap company {
            get {
                object obj = ResourceManager.GetObject("company", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap company_enabled {
            get {
                object obj = ResourceManager.GetObject("company_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CompositionProducts {
            get {
                object obj = ResourceManager.GetObject("CompositionProducts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CompositionProducts_enabled {
            get {
                object obj = ResourceManager.GetObject("CompositionProducts_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap currency {
            get {
                object obj = ResourceManager.GetObject("currency", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap currency_enabled {
            get {
                object obj = ResourceManager.GetObject("currency_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap customer {
            get {
                object obj = ResourceManager.GetObject("customer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap customer_enabled {
            get {
                object obj = ResourceManager.GetObject("customer_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap customer_price {
            get {
                object obj = ResourceManager.GetObject("customer_price", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap customer_price_enabled {
            get {
                object obj = ResourceManager.GetObject("customer_price_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap customer_reported {
            get {
                object obj = ResourceManager.GetObject("customer_reported", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap customer_reported_enabled {
            get {
                object obj = ResourceManager.GetObject("customer_reported_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap department {
            get {
                object obj = ResourceManager.GetObject("department", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap department_enabled {
            get {
                object obj = ResourceManager.GetObject("department_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap deposit {
            get {
                object obj = ResourceManager.GetObject("deposit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap deposit_enabled {
            get {
                object obj = ResourceManager.GetObject("deposit_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap depositArr {
            get {
                object obj = ResourceManager.GetObject("depositArr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap depositArr_enabled {
            get {
                object obj = ResourceManager.GetObject("depositArr_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap depositArrSearch {
            get {
                object obj = ResourceManager.GetObject("depositArrSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap depositArrSearch_enabled {
            get {
                object obj = ResourceManager.GetObject("depositArrSearch_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DepositNotify {
            get {
                object obj = ResourceManager.GetObject("DepositNotify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DepositNotify_enabled {
            get {
                object obj = ResourceManager.GetObject("DepositNotify_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap depositSearch {
            get {
                object obj = ResourceManager.GetObject("depositSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap depositSearch_enabled {
            get {
                object obj = ResourceManager.GetObject("depositSearch_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DownLoadCustomerDrawing {
            get {
                object obj = ResourceManager.GetObject("DownLoadCustomerDrawing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DownLoadCustomerDrawing_enabled {
            get {
                object obj = ResourceManager.GetObject("DownLoadCustomerDrawing_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exchange {
            get {
                object obj = ResourceManager.GetObject("exchange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exchange_enabled {
            get {
                object obj = ResourceManager.GetObject("exchange_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap find {
            get {
                object obj = ResourceManager.GetObject("find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap find_over {
            get {
                object obj = ResourceManager.GetObject("find_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hs_code {
            get {
                object obj = ResourceManager.GetObject("hs_code", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hs_code_enabled {
            get {
                object obj = ResourceManager.GetObject("hs_code_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Inventory {
            get {
                object obj = ResourceManager.GetObject("Inventory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Inventory_enabled {
            get {
                object obj = ResourceManager.GetObject("Inventory_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InventorySearch {
            get {
                object obj = ResourceManager.GetObject("InventorySearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InventorySearch_enabled {
            get {
                object obj = ResourceManager.GetObject("InventorySearch_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InventoryStart {
            get {
                object obj = ResourceManager.GetObject("InventoryStart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InventoryStart_enabled {
            get {
                object obj = ResourceManager.GetObject("InventoryStart_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap invoicing_summary_ {
            get {
                object obj = ResourceManager.GetObject("invoicing_summary ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap invoicing_summary_enabled {
            get {
                object obj = ResourceManager.GetObject("invoicing_summary_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap line_delete {
            get {
                object obj = ResourceManager.GetObject("line_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap line_delete_over {
            get {
                object obj = ResourceManager.GetObject("line_delete_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap line_download {
            get {
                object obj = ResourceManager.GetObject("line_download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap line_download_over {
            get {
                object obj = ResourceManager.GetObject("line_download_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap line_find {
            get {
                object obj = ResourceManager.GetObject("line_find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap line_find_over {
            get {
                object obj = ResourceManager.GetObject("line_find_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap line_upload {
            get {
                object obj = ResourceManager.GetObject("line_upload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap line_upload_over {
            get {
                object obj = ResourceManager.GetObject("line_upload_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap location {
            get {
                object obj = ResourceManager.GetObject("location", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap location_enabled {
            get {
                object obj = ResourceManager.GetObject("location_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap machine {
            get {
                object obj = ResourceManager.GetObject("machine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap machine_enabled {
            get {
                object obj = ResourceManager.GetObject("machine_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menu_border {
            get {
                object obj = ResourceManager.GetObject("menu_border", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menuline {
            get {
                object obj = ResourceManager.GetObject("menuline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap names {
            get {
                object obj = ResourceManager.GetObject("names", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap names_enabled {
            get {
                object obj = ResourceManager.GetObject("names_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OEM_product_management {
            get {
                object obj = ResourceManager.GetObject("OEM_product_management", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OEM_product_management_enabled {
            get {
                object obj = ResourceManager.GetObject("OEM_product_management_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OEM_sales_performance {
            get {
                object obj = ResourceManager.GetObject("OEM_sales_performance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OEM_sales_performance_enabled {
            get {
                object obj = ResourceManager.GetObject("OEM_sales_performance_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap orderAlloation {
            get {
                object obj = ResourceManager.GetObject("orderAlloation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap orderAlloation_enabled {
            get {
                object obj = ResourceManager.GetObject("orderAlloation_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap orderCopy {
            get {
                object obj = ResourceManager.GetObject("orderCopy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap orderCopy_enabled {
            get {
                object obj = ResourceManager.GetObject("orderCopy_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap orderEntry {
            get {
                object obj = ResourceManager.GetObject("orderEntry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap orderEntry_enabled {
            get {
                object obj = ResourceManager.GetObject("orderEntry_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap orderModify {
            get {
                object obj = ResourceManager.GetObject("orderModify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap orderModify_enabled {
            get {
                object obj = ResourceManager.GetObject("orderModify_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap orderSearch {
            get {
                object obj = ResourceManager.GetObject("orderSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap orderSearch_enabled {
            get {
                object obj = ResourceManager.GetObject("orderSearch_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap orderVerify {
            get {
                object obj = ResourceManager.GetObject("orderVerify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap orderVerify_enabled {
            get {
                object obj = ResourceManager.GetObject("orderVerify_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Parts {
            get {
                object obj = ResourceManager.GetObject("Parts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Parts_enabled {
            get {
                object obj = ResourceManager.GetObject("Parts_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap payment {
            get {
                object obj = ResourceManager.GetObject("payment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap payment_enabled {
            get {
                object obj = ResourceManager.GetObject("payment_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paymentSearch {
            get {
                object obj = ResourceManager.GetObject("paymentSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paymentSearch_enabled {
            get {
                object obj = ResourceManager.GetObject("paymentSearch_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProduceProduct {
            get {
                object obj = ResourceManager.GetObject("ProduceProduct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProduceProduct_enabled {
            get {
                object obj = ResourceManager.GetObject("ProduceProduct_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap product {
            get {
                object obj = ResourceManager.GetObject("product", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap product_enabled {
            get {
                object obj = ResourceManager.GetObject("product_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap product_group {
            get {
                object obj = ResourceManager.GetObject("product_group", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap product_group_enabled {
            get {
                object obj = ResourceManager.GetObject("product_group_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap product_parts {
            get {
                object obj = ResourceManager.GetObject("product_parts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap product_parts_enabled {
            get {
                object obj = ResourceManager.GetObject("product_parts_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap product_unit {
            get {
                object obj = ResourceManager.GetObject("product_unit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap product_unit_enabled {
            get {
                object obj = ResourceManager.GetObject("product_unit_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProductBuild {
            get {
                object obj = ResourceManager.GetObject("ProductBuild", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProductBuild_enabled {
            get {
                object obj = ResourceManager.GetObject("ProductBuild_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProductBuildSearch {
            get {
                object obj = ResourceManager.GetObject("ProductBuildSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProductBuildSearch_enabled {
            get {
                object obj = ResourceManager.GetObject("ProductBuildSearch_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Production {
            get {
                object obj = ResourceManager.GetObject("Production", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Production_enabled {
            get {
                object obj = ResourceManager.GetObject("Production_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProductionNotification {
            get {
                object obj = ResourceManager.GetObject("ProductionNotification", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProductionNotification_enabled {
            get {
                object obj = ResourceManager.GetObject("ProductionNotification_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProductionPlan {
            get {
                object obj = ResourceManager.GetObject("ProductionPlan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProductionPlan_enabled {
            get {
                object obj = ResourceManager.GetObject("ProductionPlan_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProductionPlanSearch {
            get {
                object obj = ResourceManager.GetObject("ProductionPlanSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProductionPlanSearch_enabled {
            get {
                object obj = ResourceManager.GetObject("ProductionPlanSearch_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProductionSchedule {
            get {
                object obj = ResourceManager.GetObject("ProductionSchedule", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProductionSchedule_enabled {
            get {
                object obj = ResourceManager.GetObject("ProductionSchedule_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProductRelieve {
            get {
                object obj = ResourceManager.GetObject("ProductRelieve", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProductRelieve_enabled {
            get {
                object obj = ResourceManager.GetObject("ProductRelieve_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProductRelieveSearch {
            get {
                object obj = ResourceManager.GetObject("ProductRelieveSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProductRelieveSearch_enabled {
            get {
                object obj = ResourceManager.GetObject("ProductRelieveSearch_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap purchase {
            get {
                object obj = ResourceManager.GetObject("purchase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap purchase_enabled {
            get {
                object obj = ResourceManager.GetObject("purchase_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PurchaseOrderEntry {
            get {
                object obj = ResourceManager.GetObject("PurchaseOrderEntry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PurchaseOrderEntry_enabled {
            get {
                object obj = ResourceManager.GetObject("PurchaseOrderEntry_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PurchaseOrderSearch {
            get {
                object obj = ResourceManager.GetObject("PurchaseOrderSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PurchaseOrderSearch_enabled {
            get {
                object obj = ResourceManager.GetObject("PurchaseOrderSearch_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PurchaseOrderSupplementEntry {
            get {
                object obj = ResourceManager.GetObject("PurchaseOrderSupplementEntry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PurchaseOrderSupplementEntry_enabled {
            get {
                object obj = ResourceManager.GetObject("PurchaseOrderSupplementEntry_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PurchaseOrderSupplementSearch {
            get {
                object obj = ResourceManager.GetObject("PurchaseOrderSupplementSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PurchaseOrderSupplementSearch_enabled {
            get {
                object obj = ResourceManager.GetObject("PurchaseOrderSupplementSearch_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap purchaseSearch {
            get {
                object obj = ResourceManager.GetObject("purchaseSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap purchaseSearch_enabled {
            get {
                object obj = ResourceManager.GetObject("purchaseSearch_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Quotation {
            get {
                object obj = ResourceManager.GetObject("Quotation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Quotation_enabled {
            get {
                object obj = ResourceManager.GetObject("Quotation_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QuotationSearch {
            get {
                object obj = ResourceManager.GetObject("QuotationSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QuotationSearch_enabled {
            get {
                object obj = ResourceManager.GetObject("QuotationSearch_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reason {
            get {
                object obj = ResourceManager.GetObject("reason", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reason_enabled {
            get {
                object obj = ResourceManager.GetObject("reason_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Receipt {
            get {
                object obj = ResourceManager.GetObject("Receipt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Receipt_enabled {
            get {
                object obj = ResourceManager.GetObject("Receipt_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap receiptMatch {
            get {
                object obj = ResourceManager.GetObject("receiptMatch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap receiptMatch_enabled {
            get {
                object obj = ResourceManager.GetObject("receiptMatch_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap receiptMatchSearch {
            get {
                object obj = ResourceManager.GetObject("receiptMatchSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap receiptMatchSearch_enabled {
            get {
                object obj = ResourceManager.GetObject("receiptMatchSearch_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReceiptSearch {
            get {
                object obj = ResourceManager.GetObject("ReceiptSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReceiptSearch_enabled {
            get {
                object obj = ResourceManager.GetObject("ReceiptSearch_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReceivingNotify {
            get {
                object obj = ResourceManager.GetObject("ReceivingNotify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReceivingNotify_enabled {
            get {
                object obj = ResourceManager.GetObject("ReceivingNotify_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap roles {
            get {
                object obj = ResourceManager.GetObject("roles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap roles_enabled {
            get {
                object obj = ResourceManager.GetObject("roles_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap safety_stock {
            get {
                object obj = ResourceManager.GetObject("safety_stock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap safety_stock_enabled {
            get {
                object obj = ResourceManager.GetObject("safety_stock_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sales {
            get {
                object obj = ResourceManager.GetObject("sales", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sales_enabled {
            get {
                object obj = ResourceManager.GetObject("sales_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap salesSearch {
            get {
                object obj = ResourceManager.GetObject("salesSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap salesSearch_enabled {
            get {
                object obj = ResourceManager.GetObject("salesSearch_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_over {
            get {
                object obj = ResourceManager.GetObject("save_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap seq {
            get {
                object obj = ResourceManager.GetObject("seq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap seq_enabled {
            get {
                object obj = ResourceManager.GetObject("seq_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shipment {
            get {
                object obj = ResourceManager.GetObject("Shipment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shipment_enabled {
            get {
                object obj = ResourceManager.GetObject("Shipment_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ShipmentSearch {
            get {
                object obj = ResourceManager.GetObject("ShipmentSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ShipmentSearch_enabled {
            get {
                object obj = ResourceManager.GetObject("ShipmentSearch_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sliptype {
            get {
                object obj = ResourceManager.GetObject("sliptype", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sliptype_enabled {
            get {
                object obj = ResourceManager.GetObject("sliptype_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Specification {
            get {
                object obj = ResourceManager.GetObject("Specification", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Specification_enabled {
            get {
                object obj = ResourceManager.GetObject("Specification_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StockAdjustment {
            get {
                object obj = ResourceManager.GetObject("StockAdjustment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StockAdjustment_enabled {
            get {
                object obj = ResourceManager.GetObject("StockAdjustment_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StockAdjustmentSearch {
            get {
                object obj = ResourceManager.GetObject("StockAdjustmentSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StockAdjustmentSearch_enabled {
            get {
                object obj = ResourceManager.GetObject("StockAdjustmentSearch_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StockNotify {
            get {
                object obj = ResourceManager.GetObject("StockNotify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StockNotify_enabled {
            get {
                object obj = ResourceManager.GetObject("StockNotify_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StockSearch {
            get {
                object obj = ResourceManager.GetObject("StockSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StockSearch_enabled {
            get {
                object obj = ResourceManager.GetObject("StockSearch_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap supplier {
            get {
                object obj = ResourceManager.GetObject("supplier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap supplier_enabled {
            get {
                object obj = ResourceManager.GetObject("supplier_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap supplier_price {
            get {
                object obj = ResourceManager.GetObject("supplier_price", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap supplier_price_enabled {
            get {
                object obj = ResourceManager.GetObject("supplier_price_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SupplierDeposit {
            get {
                object obj = ResourceManager.GetObject("SupplierDeposit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SupplierDeposit_enabled {
            get {
                object obj = ResourceManager.GetObject("SupplierDeposit_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap supplierDepositArr {
            get {
                object obj = ResourceManager.GetObject("supplierDepositArr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap supplierDepositArr_enabled {
            get {
                object obj = ResourceManager.GetObject("supplierDepositArr_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap supplierDepositArrSearch {
            get {
                object obj = ResourceManager.GetObject("supplierDepositArrSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap supplierDepositArrSearch_enabled {
            get {
                object obj = ResourceManager.GetObject("supplierDepositArrSearch_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap supplierDepositSearch {
            get {
                object obj = ResourceManager.GetObject("supplierDepositSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap supplierDepositSearch_enabled {
            get {
                object obj = ResourceManager.GetObject("supplierDepositSearch_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap taxation {
            get {
                object obj = ResourceManager.GetObject("taxation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap taxation_enabled {
            get {
                object obj = ResourceManager.GetObject("taxation_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TransferReceipt {
            get {
                object obj = ResourceManager.GetObject("TransferReceipt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TransferReceipt_enabled {
            get {
                object obj = ResourceManager.GetObject("TransferReceipt_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TransferReceiptSearch {
            get {
                object obj = ResourceManager.GetObject("TransferReceiptSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TransferReceiptSearch_enabled {
            get {
                object obj = ResourceManager.GetObject("TransferReceiptSearch_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unit {
            get {
                object obj = ResourceManager.GetObject("unit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unit_enabled {
            get {
                object obj = ResourceManager.GetObject("unit_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unPaymentSearch {
            get {
                object obj = ResourceManager.GetObject("unPaymentSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unPaymentSearch_enabled {
            get {
                object obj = ResourceManager.GetObject("unPaymentSearch_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unReceiptMatchSearch {
            get {
                object obj = ResourceManager.GetObject("unReceiptMatchSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unReceiptMatchSearch_enabled {
            get {
                object obj = ResourceManager.GetObject("unReceiptMatchSearch_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UpLoadProductionDrawing {
            get {
                object obj = ResourceManager.GetObject("UpLoadProductionDrawing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UpLoadProductionDrawing_enabled {
            get {
                object obj = ResourceManager.GetObject("UpLoadProductionDrawing_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user {
            get {
                object obj = ResourceManager.GetObject("user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user_enabled {
            get {
                object obj = ResourceManager.GetObject("user_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap userRoles {
            get {
                object obj = ResourceManager.GetObject("userRoles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap userRoles_enabled {
            get {
                object obj = ResourceManager.GetObject("userRoles_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap warehouse {
            get {
                object obj = ResourceManager.GetObject("warehouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap warehouse_enabled {
            get {
                object obj = ResourceManager.GetObject("warehouse_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
